apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jetono.role.name" . }}
  labels: {{ include "jetono.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create"]
