apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jetonoApiRoleBinding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "jetono.role.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jetono.serviceAccountName" . }}
