apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jetono.role.name" . }}
  labels: {{ include "jetono.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
# configmaps is used in kubernetes-ful mode of jetono
# jetono stores contexts in configmaps.
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "update", "delete"]
