version: "3.7"

services:
  jetono-api:
    container_name: jetono-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - NKEYS_PATH=/nsc/keys
      - NSC_HOME=/nsc/home
      - NSC_STORE=/nsc/store
      - JETONO_STORE_TYPE=objectbox
      - OBJECTBOX_VOL=/mnt/objectbox
    ports:
      - "8080:1323"
    volumes:
      - ./nsc:/nsc
