version: "3.7"

services:
  jetono-api:
    container_name: jetono-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - NKEYS_PATH=/nsc/keys
      - NSC_HOME=/nsc/home
      - NSC_STORE=/nsc/store
      - JETONO_STORE_TYPE=objectbox
      - OBJECTBOX_VOL=/mnt/objectbox
    ports:
      - "8080:1323"
    volumes:
      - ./nsc:/nsc
  nats:
    container_name: nats
    image: nats
    ports:
      - "4222:4222"
      - "9000:9000"
      - "8222:8222"
    volumes:
        - ./docker/nats-server.conf:/etc/nats/nats-server.conf
    command: ["--config", "/etc/nats/nats-server.conf"]
