// Code generated by ObjectBox; DO NOT EDIT.

package storage

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(AccountServerMapBBinding)
	model.LastEntityId(1, 1090041196471887670)
	model.LastIndexId(1, 976550826644671096)

	return model
}
