apiVersion: v1
kind: Service
metadata:
  name: {{ include "jetono.fullname" . }}
  labels:
    {{- include "jetono.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "jetono.selectorLabels" . | nindent 4 }}
