// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bind": {
            "get": {
                "description": "Returns json object with context",
                "tags": [
                    "Account"
                ],
                "summary": "read context bound to account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator description",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Returns json with confirmation",
                "tags": [
                    "Account"
                ],
                "summary": "Bind context to account",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.AccountServerMap"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator description",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/creds/operator/{operator}/account/{account}/user/{name}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Generate user credentials",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operators list",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "User was not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator": {
            "post": {
                "description": "Add an operator to the store",
                "tags": [
                    "Operator"
                ],
                "summary": "Add an operator",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/src.addOperatorForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator added",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator/{name}": {
            "get": {
                "description": "Returns json object with operator description",
                "tags": [
                    "Operator"
                ],
                "summary": "Describes an operator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator description",
                        "schema": {
                            "$ref": "#/definitions/src.OperatorDescription"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates an operator and returns json with status ok if successful",
                "tags": [
                    "Operator"
                ],
                "summary": "Updates an operator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/src.updateOperatorForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status ok",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator/{operator}/account": {
            "post": {
                "description": "Add an account with given operator to the store",
                "tags": [
                    "Account"
                ],
                "summary": "Add an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Account data in json format",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/src.addAccountForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account added",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator/{operator}/account/{account}/user": {
            "post": {
                "description": "Add user with given operator and account to the store",
                "tags": [
                    "User"
                ],
                "summary": "Add user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User added",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator/{operator}/account/{account}/user/{name}": {
            "get": {
                "description": "Returns json object with user description",
                "tags": [
                    "User"
                ],
                "summary": "Describes user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator description",
                        "schema": {
                            "$ref": "#/definitions/src.UserDescription"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Revokes a user",
                "tags": [
                    "User"
                ],
                "summary": "Revokes a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator description",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates an user and returns json with status ok if successful",
                "tags": [
                    "User"
                ],
                "summary": "Updates an user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "add tags for user - comma separated list or option can be specified multiple times",
                        "name": "tag",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "remove tag - comma separated list or option can be specified multiple times",
                        "name": "rm-tag",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "valid from ('0' is always, '3d' is three days) - yyyy-mm-dd, #m(inutes), #h(ours), #d(ays), #w(eeks), #M(onths), #y(ears)",
                        "name": "start",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "valid until ('0' is always, '2M' is two months) - yyyy-mm-dd, #m(inutes), #h(ours), #d(ays), #w(eeks), #M(onths), #y(ears)",
                        "name": "expiry",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "` + "`" + `add start-end time range of the form ",
                        "name": "time",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "` + "`" + `remove start-end time by start time ",
                        "name": "rm-time",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "set the locale with which time values are interpreted",
                        "name": "locale",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "add source network for connection - comma separated list or option can be specified multiple times",
                        "name": "source-network",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "remove source network for connection - comma separated list or option can be specified multiple times",
                        "name": "rm-source-network",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "set\tallowed\tconnection\ttypes:\t%s\t%s\t%s\t%s\t%s\t%s\t-\tcomma\tseparated\tlist\tor\toption\tcan\tbe\tspecified\tmultiple\ttimes, jwt.ConnectionTypeLeafnode, jwt.ConnectionTypeMqtt, jwt.ConnectionTypeStandard, jwt.ConnectionTypeWebsocket, jwt.ConnectionTypeLeafnodeWS, jwt.ConnectionTypeMqttWS))",
                        "name": "conn-type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "remove connection types - comma separated list or option can be specified multiple times",
                        "name": "rm-conn-type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "set maximum number of subscriptions (-1 is unlimited)",
                        "name": "subs",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "set maximum data in bytes for the user (-1 is unlimited)",
                        "name": "data",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "set maximum message payload in bytes for the account (-1 is unlimited)",
                        "name": "payload",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "no connect challenge required for user",
                        "name": "bearer",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "the amount of stime sthe s%s sis svalid s(global) - s[#ms(millis) | #s(econds) | m(inutes) | h(ours)] - sDefault sis no time limit., typeName))",
                        "name": "response-ttl",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "%s to slimit how soften sa sclient scan spublish sto sreply ssubjects\t[with an optional count, --allow-pub-response=n] (global), typeName))",
                        "name": "allow-pub-response",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "add publish s%s s- scomma sseparated slist sor soption scan sbe sspecified smultiple stimes, typeName))",
                        "name": "allow-pub",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "add publish sand ssubscribe s%s s- scomma sseparated slist sor soption scan sbe sspecified\tmultiple stimes, typeName))",
                        "name": "allow-pubsub",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "add subscribe s%s s- scomma sseparated slist sor soption scan sbe sspecified multiple stimes, typeName))",
                        "name": "allow-sub",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "add deny spublish s%s s- scomma sseparated slist sor soption scan sbe sspecified smultiple\ttimes, typeName))",
                        "name": "deny-pub",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "add deny spublish sand ssubscribe s%s s- scomma sseparated slist sor soption scan sbe sspecified multiple times, typeName))",
                        "name": "deny-pubsub",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "add deny ssubscribe s%s s- scomma sseparated slist sor soption scan sbe sspecified smultiple\ttimes, typeName))",
                        "name": "deny-sub",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "remove sresponse ssettings sfrom s%s, typeName))",
                        "name": "rm-response-perms",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "remove spublish/subscribe sand sdeny s%s - comma separated\tlist or\toption can be specified multiple times, typeName))",
                        "name": "rm",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status ok",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator/{operator}/account/{account}/users": {
            "get": {
                "description": "Returns json list of existing users for given operator's account",
                "tags": [
                    "User"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of users for given operator's account",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator/{operator}/account/{name}": {
            "get": {
                "description": "Returns json object with account description",
                "tags": [
                    "Account"
                ],
                "summary": "Describes an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator description",
                        "schema": {
                            "$ref": "#/definitions/src.AccountDescription"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates an account and returns json with status ok if successful",
                "tags": [
                    "Account"
                ],
                "summary": "Updates an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Account data in json format",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/src.updateAccountForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status ok",
                        "schema": {
                            "$ref": "#/definitions/src.SimpleJSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operator/{operator}/accounts": {
            "get": {
                "description": "Returns json list of existing accounts for given operator",
                "tags": [
                    "Account"
                ],
                "summary": "List accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operator name",
                        "name": "operator",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operator's accounts list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/operators": {
            "get": {
                "description": "Returns json list of existing operators",
                "tags": [
                    "Operator"
                ],
                "summary": "List operators",
                "responses": {
                    "200": {
                        "description": "Operators list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "src.AccountDescription": {
            "type": "object",
            "properties": {
                "iat": {
                    "type": "integer"
                },
                "iss": {
                    "type": "string"
                },
                "jti": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nats": {
                    "type": "object",
                    "properties": {
                        "authorization": {
                            "type": "object",
                            "properties": {
                                "auth_users": {}
                            }
                        },
                        "default_permissions": {
                            "type": "object",
                            "properties": {
                                "pub": {
                                    "type": "object",
                                    "additionalProperties": true
                                },
                                "sub": {
                                    "type": "object",
                                    "additionalProperties": true
                                }
                            }
                        },
                        "limits": {
                            "type": "object",
                            "properties": {
                                "conn": {
                                    "type": "integer"
                                },
                                "data": {
                                    "type": "integer"
                                },
                                "exports": {
                                    "type": "integer"
                                },
                                "imports": {
                                    "type": "integer"
                                },
                                "leaf": {
                                    "type": "integer"
                                },
                                "payload": {
                                    "type": "integer"
                                },
                                "subs": {
                                    "type": "integer"
                                },
                                "wildcards": {
                                    "type": "boolean"
                                }
                            }
                        },
                        "type": {
                            "type": "string"
                        },
                        "version": {
                            "type": "integer"
                        }
                    }
                },
                "sub": {
                    "type": "string"
                }
            }
        },
        "src.OperatorDescription": {
            "type": "object",
            "properties": {
                "iat": {
                    "type": "integer"
                },
                "iss": {
                    "type": "string"
                },
                "jti": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nats": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string"
                        },
                        "version": {
                            "type": "integer"
                        }
                    }
                },
                "sub": {
                    "type": "string"
                }
            }
        },
        "src.SimpleJSONResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "src.UserDescription": {
            "type": "object",
            "properties": {
                "iat": {
                    "type": "integer"
                },
                "iss": {
                    "type": "string"
                },
                "jti": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nats": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "integer"
                        },
                        "payload": {
                            "type": "integer"
                        },
                        "pub": {
                            "type": "object",
                            "additionalProperties": true
                        },
                        "sub": {
                            "type": "object",
                            "additionalProperties": true
                        },
                        "subs": {
                            "type": "integer"
                        },
                        "type": {
                            "type": "string"
                        },
                        "version": {
                            "type": "integer"
                        }
                    }
                },
                "sub": {
                    "type": "string"
                }
            }
        },
        "src.addAccountForm": {
            "type": "object",
            "properties": {
                "allow_pub": {
                    "type": "string"
                },
                "allow_pub_response": {
                    "type": "string"
                },
                "allow_pubsub": {
                    "type": "string"
                },
                "allow_sub": {
                    "type": "string"
                },
                "deny_pub": {
                    "type": "string"
                },
                "deny_pubsub": {
                    "type": "string"
                },
                "deny_sub": {
                    "type": "string"
                },
                "expiry": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "response_ttl": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "src.addOperatorForm": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "force": {
                    "type": "boolean"
                },
                "generate_signing_key": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "sys": {
                    "type": "boolean"
                }
            }
        },
        "src.updateAccountForm": {
            "type": "object",
            "properties": {
                "conns": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "disallow_bearer": {
                    "type": "boolean"
                },
                "exports": {
                    "type": "string"
                },
                "imports": {
                    "type": "string"
                },
                "info_url": {
                    "type": "string"
                },
                "js_consumer": {
                    "type": "string"
                },
                "js_disk_storage": {
                    "type": "string"
                },
                "js_max_ack_pending": {
                    "type": "string"
                },
                "js_max_bytes_required": {
                    "type": "string"
                },
                "js_max_disk_stream": {
                    "type": "string"
                },
                "js_max_mem_stream": {
                    "type": "string"
                },
                "js_mem_storage": {
                    "type": "string"
                },
                "js_streams": {
                    "type": "string"
                },
                "js_tier": {
                    "type": "string"
                },
                "leaf_conns": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "rm_js_tier": {
                    "type": "string"
                },
                "rm_sk": {
                    "type": "string"
                },
                "rm_tag": {
                    "type": "string"
                },
                "subscriptions": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "wildcard_exports": {
                    "type": "boolean"
                }
            }
        },
        "src.updateOperatorForm": {
            "type": "object",
            "properties": {
                "account_jwt_server_url": {
                    "type": "string"
                },
                "require_signing_keys": {
                    "type": "boolean"
                },
                "rm_account_jwt_server_url": {
                    "type": "string"
                },
                "rm_service_url": {
                    "type": "string"
                },
                "rm_tag": {
                    "type": "string"
                },
                "service_url": {
                    "type": "string"
                },
                "system_account": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "storage.AccountServerMap": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "servers": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
